modLoader = "javafml"
loaderVersion = "[43,)"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "thermal_science"
version = "${file.jarVersion}"
displayName = "Thermal Science"
#logoFile="examplemod.png"
itemIcon="thermal_science:machine_assembly"
credits = "Team CoFH"
authors = "dr0n1k"
description = '''
Contains the items, blocks and random staff of the Thermal Series
'''

[[dependencies.thermal_science]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_science]]
modId = "forge"
mandatory = true
versionRange = "[43.2.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_science]]
modId = "cofh_core"
mandatory = true
versionRange = "[10.0, 10.1]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_science]]
modId = "thermal"
mandatory = true
versionRange = "[10.0, 10.1]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_science]]
modId = "thermal_expansion"
mandatory = true
versionRange = "[10.0, 10.1]"
ordering = "AFTER"
side = "BOTH"